# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75adfb1bd358b9a4ae6a714e79fca894ee607845da1fb847e9c6511f7b4fe12ad69f24dbdc144d291dd459448e5bedbf92040c9ba2315a7e55768151b4563cae

test:
  secret_key_base: 3f765b0fe4eafed03366f66de2b599854d2e8a170e6b8cf5a5abffb3a33dc6ea3a657035aded856bd1fa88b1404c05661a7ac4982231cce672292e9865f7bd1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
